name: gbt_identity
description: A starting point for Dart libraries or applications.
version: 4.1.0

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
